name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install project (minimal)
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Run Ruff
        run: |
          ruff check .

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install system deps (FAISS)
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run tests with coverage
        run: |
          pytest --cov --cov-report=term-missing -q

      - name: Upload coverage & test cache (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts-${{ matrix.python-version }}
          path: |
            ./.pytest_cache
            ./.coverage
          if-no-files-found: ignore
